DROP DATABASE IF EXISTS betting;
CREATE DATABASE betting;
USE betting;

CREATE TABLE `User` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    isAdmin BOOLEAN NOT NULL
) ENGINE=InnoDB;
